apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.58.0/bundle.yaml
- rbac.yaml
- prometheus.yaml
- service.yaml